---
#  - name: Copy mongodb repository 
#    copy: 
#      src: roles/mongodbserver/files/mongodb-org-5.0.repo 
#      dest: /etc/yum.repos.d/mongodb-org-5.0.repo

- name: Copy mongodb repository 
  template:
    src: mongodb-org-5.0.repo.j2
    dest: /etc/yum.repos.d/mongodb-org-5.0.repo

 - name: Install mongodb
   yum: 
     name: mongodb-org 
     state: present
   notify: 
     - start mongodb
   
